export const pricing = [
  {
    type: 'Starter',
    description: 'Ideal for freelancers and contractors just starting out.',
    price: 24,
    features: [
      'All Templates',
      'Unlimited Clients & Projects',
      'Invoicing & Payments',
      'Proposals & Contracts',
      'Tasks & Time Tracking',
      'Client CRM',
      'Expense Tracking',
      'Up to 5 Project Collaborators',
    ],
  },
  {
    type: 'Professional',
    description: 'Everything a growing independent business needs to thrive.',
    price: 39,
    features: [
      'Everything in Starter plus...',
      'Custom Branding',
      'Forms & Questionnaires',
      'Workflow Automations',
      'Client Portal',
      'QuickBooks Integration',
      'Calendly Integration',
      'Zapier Integration',
      'Up to 15 Project Collaborators',
    ],
  },
  {
    type: 'Business',
    description: 'The perfect package for small businesses and agencies.',
    price: 79,
    features: [
      'Everything in Starter and Professional plus...',
      'Subcontractor Management',
      'Hiring Agreement Templates (1099 contracts)',
      'Subcontractor Onboarding',
      'Talent Pool',
      '3 Team Seats (additional seats $9/month)',
      'Accountant Access',
      'Connect Multiple Bank Accounts',
      'Unlimited Subcontractors',
      'Unlimited Project Collaborators',
    ],
  },
];
